### ISSUE TITLE
phased_lstm_keras problem? add_weight () got multiple values for argument 'name'

### ISSUE THREAD

**Issue by jabowery** [abr/lmu#10]
See https://github.com/fferroni/PhasedLSTM-Keras/issues/19

**Comment by arvoelke** [comment]
At first glance this looks like some sort of versioning issue in `phased_lstm_keras`, which is a separate package. Could you please report the issue there (https://github.com/fferroni/PhasedLSTM-Keras/issues) and let them know what version of keras you're using? If you link it here I can keep an eye on it in case I need to add some sort of version limit to the requirements. I don't think this will affect the `LMUCell`. Thanks!

**Comment by jabowery** [comment]
Moved and linked as requested.

**Comment by arvoelke** [comment]
Closing as this has been moved to the `paper` branch which is unlikely to change, and this example was removed in #18, which is released on pypi (`pip install lmu==0.1.0`; https://pypi.org/project/lmu/).
