### ISSUE TITLE
allow_growth to permit parallel notebook kernels?

### ISSUE THREAD

**Issue by jabowery** [abr/lmu#13]
In order to run multiple `notebooks` at once, I've found it necessary to preface them with:

```
import tensorflow as tf
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
tf.Session(config=config)
```

**Comment by arvoelke** [comment]
That's certainly good to know (I had always been disconnecting one kernel before starting the other). I'll keep this open as a reminder to myself to integrate it into the documentation as this develops. Thanks!

**Comment by arvoelke** [comment]
I'm closing this for now as we will be reworking the documentation moving forwards with each major release, and this is more of a general aspect of using jupyter+TF+GPU than it is something about this repository. Thanks for letting us know!
