### ISSUE TITLE
Upgrade to TensorFlow 2

### ISSUE THREAD

**Issue by arvoelke** [abr/lmu#16]
and ensure all examples still perform well

**Comment by jabowery** [comment]
It would be great if the examples could be opened with [the Chrome Open with Colab extension](https://chrome.google.com/webstore/detail/open-in-colab).

**Comment by arvoelke** [comment]
Resolved by #18, which is released on pypi (`pip install lmu==0.1.0`; https://pypi.org/project/lmu/).
